def raise_exception_msg(message = "C is fun"):
    print NameError("This is a name exception!")